name: Deploy to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: electrow/comp7940_group:latest
        build-args: |
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          COSMOSDB_URL=${{ secrets.COSMOSDB_URL }}
          COSMOSDB_KEY=${{ secrets.COSMOSDB_KEY }}
    - name: Deploy to Fly.io
      uses: actions/checkout@v3
      uses: superfly/flyctl-actions/setup-flyctl@master
      run: |
        flyctl deploy --image electrow/comp7940_group:latest -a group7940
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
